DAOS-14657 test: ftest for libpil4dfs with fio
Support of fio with ansible ftest deployment script.

Required-githooks: true
Signed-off-by: Cedric Koch-Hofer <cedric.koch-hofer@intel.com>

diff --git a/utils/ansible/ftest/templates/daos-make.sh.j2 b/utils/ansible/ftest/templates/daos-make.sh.j2
--- a/utils/ansible/ftest/templates/daos-make.sh.j2
+++ b/utils/ansible/ftest/templates/daos-make.sh.j2
@@ -116,6 +116,7 @@ function usage
 		       --vol-daos <path>	Path of vol-daos source tree
 		       --mpifileutils <path>    Path of mpi file utils source tree
 		       --ior <path>             Path of ior file utils source tree
+		       --fio <path>             Path of fio file utils source tree
 		   -j, --jobs <job>             Allow N jobs at once; one job with no arg
 		   -f, --force                  Overwrite the current install of DAOS
 		   -h, --help                   Show this help message and exit
@@ -140,7 +141,7 @@ function run
 	fi
 }
 
-OPTIONS=$(getopt -o "j:fhVvDq" --long "mpich:,hdf5:,vol-daos:,mpifileutils:,ior:,jobs:,force,help,version,verbose,debug,quiet" -- "$@") || exit 1
+OPTIONS=$(getopt -o "j:fhVvDq" --long "mpich:,hdf5:,vol-daos:,mpifileutils:,ior,fio:,jobs:,force,help,version,verbose,debug,quiet" -- "$@") || exit 1
 eval set -- "$OPTIONS"
 while true
 do
@@ -150,6 +151,7 @@ do
 		--vol-daos) VOL_DAOS_PATH="$2" ; shift 2 ;;
 		--mpifileutils) MPI_FILE_UTILS_PATH="$2" ; shift 2 ;;
 		--ior) IOR_PATH="$2" ; shift 2 ;;
+		--fio) FIO_PATH="$2" ; shift 2 ;;
 		-j|--jobs) JOBS_NB="$2" ; shift 2 ;;
 		-f|--force) FORCE_INSTALL=true ; shift 1;;
 		-h|--help) usage ; exit 0;;
@@ -532,6 +534,32 @@ if [[ $IOR_PATH ]] ; then
 			--with-mpiio)
 
 		run ../configure "${IOR_CONFIGURE_OPTS[@]}"
+	fi
+
+	run env CFLAGS="-g -O0" make -j $(nproc) install
+
+	popd > /dev/null
+fi
+
+if [[ $FIO_PATH ]] ; then
+	info "Building and installing FIO from source tree $FIO_PATH to $DAOS_INSTALL_DIR"
+
+	if [[ ! -f "$FIO_PATH/fio.c" ]] ; then
+		fatal "Invalid FIO: path=$FIO_PATH"
+	fi
+
+	if [[ "$CMD" == install && -n "$FORCE_INSTALL" ]] ; then
+		info "Removing old FIO install"
+		if ! run rm -fr "$FIO/build" ; then
+			fatal "Old install of FIO could not be removed"
+		fi
+	fi
+
+	run mkdir -p "$FIO_PATH/build"
+	pushd "$FIO_PATH/build" > /dev/null
+
+	if [[ ! -f "$FIO_PATH/build/Makefile" ]] ; then
+		run env CFLAGS="-I$DAOS_INSTALL_DIR/include" LDFLAGS="-L$DAOS_INSTALL_DIR/lib64" ../configure --prefix="$DAOS_INSTALL_DIR"
 	fi
 
 	run env CFLAGS="-g -O0" make -j $(nproc) install
