DAOS-14657 test: ftest for libpil4dfs with fio
Miscellaneous fixes:
- remove pip install
- fix template of bash script

Skip-func-hw-test-medium-md-on-ssd: false
Test-tag: Pil4dfsFio,test_pil4dfs_vs_dfs
Required-githooks: true
Signed-off-by: Cedric Koch-Hofer <cedric.koch-hofer@intel.com>

diff --git a/utils/ansible/ftest/templates/daos-make.sh.j2 b/utils/ansible/ftest/templates/daos-make.sh.j2
--- a/utils/ansible/ftest/templates/daos-make.sh.j2
+++ b/utils/ansible/ftest/templates/daos-make.sh.j2
@@ -169,7 +169,7 @@ done
 
 [[ ${1:+x} ]] || fatal "Command not defined: use install or update"
 CMD="$1"
-[[ ${VALID_CMDS[$CMD]} == true ]] || fatal "Invalid command \"$CMD\": use install or update"
+${VALID_CMDS[$CMD]} || fatal "Invalid command \"$CMD\": use install or update"
 
 check_cmds $SCONS_EXE $MODULE_EXE $CLUSH_EXE $WGET_EXE $MAKE_EXE $CMAKE_EXE
 
@@ -185,7 +185,7 @@ run $CLUSH_EXE $CLUSH_OPTS -w $SERVERS_LIST mountpoint --quiet "$HOME"
 for dir in "$DAOS_INSTALL_DIR" "$DAOS_SOURCE_DIR/build"
 do
 	if [[ -d "$dir" && "$CMD" == install ]]; then
-		[[ "$FORCE_INSTALL" == "true" ]] || fatal "DAOS already installed: use install --force or update."
+		"$FORCE_INSTALL" || fatal "DAOS already installed: use install --force or update."
 		info "Removing old DAOS install directory $dir"
 		if ! run /bin/rm -fr "$dir" ; then
 			fatal "Old install directory $dir could not be removed"
@@ -254,7 +254,7 @@ if [[ ${MPICH_PATH:+x} ]] ; then
 		fatal "Invalid MPICH directory: path=$MPICH_PATH"
 	fi
 
-	if [[ "$CMD" == install && "$FORCE_INSTALL" == "true" ]] ; then
+	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
 		info "Removing old MPICH install"
 		if ! run rm -fr "$MPICH_PATH/build" "$MPICH_PATH/configure" ; then
 			fatal "Old install of MPICH could not be removed"
@@ -351,7 +351,7 @@ if [[ ${HDF5_PATH:+x} ]] ; then
 		fatal "Invalid HDF5 directory: path=$HDF5_PATH"
 	fi
 
-	if [[ "$CMD" == install && "$FORCE_INSTALL" == "true" ]] ; then
+	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
 		info "Removing old HDF5 install"
 		if ! run rm -fr "$HDF5_PATH/build" "$HDF5_PATH/configure" ; then
 			fatal "Old install of HDF5 could not be removed"
@@ -394,7 +394,7 @@ if [[ ${VOL_DAOS_PATH:+x} ]] ; then
 		fatal "Invalid DAOS HDF5 Volume directory: path=$VOL_DAOS_PATH"
 	fi
 
-	if [[ "$CMD" == install && "$FORCE_INSTALL" == "true" ]] ; then
+	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
 		info "Removing old DAOS HDF5 Volume install"
 		if ! run rm -fr "$VOL_DAOS_PATH/build" ; then
 			fatal "Old install of HDF5 could not be removed"
@@ -440,7 +440,7 @@ if [[ ${MPI_FILE_UTILS_PATH:+x} ]] ; then
 		fatal "Invalid MPI File Utils directory: path=$MPI_FILE_UTILS_PATH"
 	fi
 
-	if [[ "$CMD" == install && "$FORCE_INSTALL" == "true" ]] ; then
+	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
 		info "Removing old MPI File Utils install"
 		if ! run rm -fr "$MPI_FILE_UTILS_PATH/deps" "$MPI_FILE_UTILS_PATH/build" "$MPI_FILE_UTILS_PATH/configure" ; then
 			fatal "Old install of MPI File Utils could not be removed"
@@ -511,7 +511,7 @@ if [[ ${IOR_PATH:+x} ]] ; then
 		fatal "Invalid IOR directory: path=$IOR_PATH"
 	fi
 
-	if [[ "$CMD" == install && "$FORCE_INSTALL" == "true" ]] ; then
+	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
 		info "Removing old IOR install"
 		if ! run rm -fr "$IOR_PATH/build" "$IOR_PATH/configure" ; then
 			fatal "Old install of IOR could not be removed"
@@ -551,7 +551,7 @@ if [[ ${FIO_PATH:+x} ]] ; then
 		fatal "Invalid FIO: path=$FIO_PATH"
 	fi
 
-	if [[ "$CMD" == install && "$FORCE_INSTALL" == "true" ]] ; then
+	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
 		info "Removing old FIO install"
 		if ! run rm -fr "$FIO_PATH/build" ; then
 			fatal "Old install of FIO could not be removed"
