DAOS-14657 test: ftest for libpil4dfs with fio
Integrate reviewers comment:
- Remove ansible update

Skip-func-hw-test-medium-md-on-ssd: false
Test-tag: Pil4dfsFio,test_pil4dfs_vs_dfs
Required-githooks: true
Signed-off-by: Cedric Koch-Hofer <cedric.koch-hofer@intel.com>

diff --git a/utils/ansible/ftest/templates/daos-make.sh.j2 b/utils/ansible/ftest/templates/daos-make.sh.j2
--- a/utils/ansible/ftest/templates/daos-make.sh.j2
+++ b/utils/ansible/ftest/templates/daos-make.sh.j2
@@ -1,11 +1,10 @@
 #!/bin/bash
 # shellcheck disable=all # Jinja2 template can not be parsed with shellcheck
 
-set -u -o pipefail
+set -o pipefail
 
-VERSION=0.4
-CWD="$(realpath "${0%}")"
-CWD="${CWD%/*}"
+VERSION=0.3
+CWD="$(realpath "$(dirname $0)")"
 declare -A VALID_CMDS=([install]=true [update]=true)
 
 DAOS_INSTALL_DIR="{{ daos_runtime_dir }}/install"
@@ -14,7 +13,6 @@ SERVERS_LIST="{{ groups["daos_servers"] | join(',') }}"
 {% if "daos_clients" in groups and groups["daos_clients"] | length > 0 %}
 CLIENTS_LIST="{{ groups["daos_clients"] | join(',') }}"
 {% endif %}
-BUILD_TYPE="{{ daos_build_mode | default(daos_build_mode_default) }}"
 
 SCONS_EXE=scons-3
 CLUSH_EXE=clush
@@ -54,7 +52,6 @@ TRACE_LEVEL_DEBUG=2
 TRACE_LEVEL=$TRACE_LEVEL_STANDARD
 
 JOBS_NB=1
-FORCE_INSTALL="false"
 
 function debug
 {
@@ -119,7 +116,6 @@ function usage
 		       --vol-daos <path>	Path of vol-daos source tree
 		       --mpifileutils <path>    Path of mpi file utils source tree
 		       --ior <path>             Path of ior file utils source tree
-		       --fio <path>             Path of fio file utils source tree
 		   -j, --jobs <job>             Allow N jobs at once; one job with no arg
 		   -f, --force                  Overwrite the current install of DAOS
 		   -h, --help                   Show this help message and exit
@@ -144,7 +140,7 @@ function run
 	fi
 }
 
-OPTIONS=$(getopt -o "j:fhVvDq" --long "mpich:,hdf5:,vol-daos:,mpifileutils:,ior:,fio:,jobs:,force,help,version,verbose,debug,quiet" -- "$@") || exit 1
+OPTIONS=$(getopt -o "j:fhVvDq" --long "mpich:,hdf5:,vol-daos:,mpifileutils:,ior:,jobs:,force,help,version,verbose,debug,quiet" -- "$@") || exit 1
 eval set -- "$OPTIONS"
 while true
 do
@@ -154,9 +150,8 @@ do
 		--vol-daos) VOL_DAOS_PATH="$2" ; shift 2 ;;
 		--mpifileutils) MPI_FILE_UTILS_PATH="$2" ; shift 2 ;;
 		--ior) IOR_PATH="$2" ; shift 2 ;;
-		--fio) FIO_PATH="$2" ; shift 2 ;;
 		-j|--jobs) JOBS_NB="$2" ; shift 2 ;;
-		-f|--force) FORCE_INSTALL="true" ; shift 1;;
+		-f|--force) FORCE_INSTALL=true ; shift 1;;
 		-h|--help) usage ; exit 0;;
 		-V|--version) echo "daos-make.sh version=$VERSION" ; exit 0 ;;
 		-v|--verbose) TRACE_LEVEL=$TRACE_LEVEL_VERBOSE ; shift 1 ;;
@@ -167,9 +162,9 @@ do
 	esac
 done
 
-[[ ${1:+x} ]] || fatal "Command not defined: use install or update"
+[[ $1 ]] || fatal "Command not defined: use install or update"
 CMD="$1"
-${VALID_CMDS[$CMD]} || fatal "Invalid command \"$CMD\": use install or update"
+[[ ${VALID_CMDS[$CMD]} == true ]] || fatal "Invalid command \"$CMD\": use install or update"
 
 check_cmds $SCONS_EXE $MODULE_EXE $CLUSH_EXE $WGET_EXE $MAKE_EXE $CMAKE_EXE
 
@@ -185,7 +180,7 @@ run $CLUSH_EXE $CLUSH_OPTS -w $SERVERS_LIST mountpoint --quiet "$HOME"
 for dir in "$DAOS_INSTALL_DIR" "$DAOS_SOURCE_DIR/build"
 do
 	if [[ -d "$dir" && "$CMD" == install ]]; then
-		"$FORCE_INSTALL" || fatal "DAOS already installed: use install --force or update."
+		[[ -n "$FORCE_INSTALL" ]] || fatal "DAOS already installed: use install --force or update."
 		info "Removing old DAOS install directory $dir"
 		if ! run /bin/rm -fr "$dir" ; then
 			fatal "Old install directory $dir could not be removed"
@@ -210,7 +205,7 @@ case $CMD in
 esac
 
 info "Building and installing DAOS from source tree $PWD to $DAOS_INSTALL_DIR"
-if ! run env MPI_PKG=any "$SCONS_EXE" BUILD_TYPE="$BUILD_TYPE" PREFIX="$DAOS_INSTALL_DIR" install $SCONS_OPTS ; then
+if ! run env MPI_PKG=any "$SCONS_EXE" BUILD_TYPE=debug PREFIX="$DAOS_INSTALL_DIR" install $SCONS_OPTS ; then
 	fatal "DAOS could not be properly build and/or installed"
 fi
 
@@ -247,14 +242,14 @@ run $CLUSH_EXE $CLUSH_OPTS -l root -w $SERVERS_LIST rm -f /etc/ld.so.cache
 run $CLUSH_EXE $CLUSH_OPTS -l root -w $SERVERS_LIST ldconfig
 {% endif %}
 
-if [[ ${MPICH_PATH:+x} ]] ; then
+if [[ $MPICH_PATH ]] ; then
 	info "Building and installing MPICH from source tree $MPICH_PATH to $DAOS_INSTALL_DIR"
 
 	if [[ ! -f "$MPICH_PATH/mpich-doxygen.in" ]] ; then
 		fatal "Invalid MPICH directory: path=$MPICH_PATH"
 	fi
 
-	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
+	if [[ "$CMD" == install && -n "$FORCE_INSTALL" ]] ; then
 		info "Removing old MPICH install"
 		if ! run rm -fr "$MPICH_PATH/build" "$MPICH_PATH/configure" ; then
 			fatal "Old install of MPICH could not be removed"
@@ -341,17 +336,17 @@ if [[ ${MPICH_PATH:+x} ]] ; then
 		mkdir -p /usr/share/modulefiles/mpi
 		ln -fs "$DAOS_INSTALL_DIR/share/modulefiles/mpich-x86_64" /usr/share/modulefiles/mpi/mpich-x86_64
 		EOF
-	} | run $CLUSH_EXE $CLUSH_OPTS -l root -w $CLIENTS_LIST -w $SERVERS_LIST bash -s
+	} | run $CLUSH_EXE $CLUSH_OPTS -l root -w $CLIENTS_LIST bash -s
 fi
 
-if [[ ${HDF5_PATH:+x} ]] ; then
+if [[ $HDF5_PATH ]] ; then
 	info "Building and installing HDF5 from source tree $HDF5_PATH to $DAOS_INSTALL_DIR"
 
 	if [[ ! -f "$HDF5_PATH/config/libhdf5.pc.in" ]] ; then
 		fatal "Invalid HDF5 directory: path=$HDF5_PATH"
 	fi
 
-	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
+	if [[ "$CMD" == install && -n "$FORCE_INSTALL" ]] ; then
 		info "Removing old HDF5 install"
 		if ! run rm -fr "$HDF5_PATH/build" "$HDF5_PATH/configure" ; then
 			fatal "Old install of HDF5 could not be removed"
@@ -387,14 +382,14 @@ if [[ ${HDF5_PATH:+x} ]] ; then
 	popd > /dev/null
 fi
 
-if [[ ${VOL_DAOS_PATH:+x} ]] ; then
+if [[ $VOL_DAOS_PATH ]] ; then
 	info "Building and installing DAOS HDF5 Volume from source tree $VOL_DAOS_PATH to $DAOS_INSTALL_DIR"
 
 	if [[ ! -f "$VOL_DAOS_PATH/CMake/hdf5_vol_daos.pc.in" ]] ; then
 		fatal "Invalid DAOS HDF5 Volume directory: path=$VOL_DAOS_PATH"
 	fi
 
-	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
+	if [[ "$CMD" == install && -n "$FORCE_INSTALL" ]] ; then
 		info "Removing old DAOS HDF5 Volume install"
 		if ! run rm -fr "$VOL_DAOS_PATH/build" ; then
 			fatal "Old install of HDF5 could not be removed"
@@ -433,14 +428,14 @@ if [[ ${VOL_DAOS_PATH:+x} ]] ; then
 	popd > /dev/null
 fi
 
-if [[ ${MPI_FILE_UTILS_PATH:+x} ]] ; then
+if [[ $MPI_FILE_UTILS_PATH ]] ; then
 	info "Building and installing MPI File Utils from source tree $MPI_FILE_UTILS_PATH to $DAOS_INSTALL_DIR"
 
 	if [[ ! -f "$MPI_FILE_UTILS_PATH/mpifileutils.spec" ]] ; then
 		fatal "Invalid MPI File Utils directory: path=$MPI_FILE_UTILS_PATH"
 	fi
 
-	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
+	if [[ "$CMD" == install && -n "$FORCE_INSTALL" ]] ; then
 		info "Removing old MPI File Utils install"
 		if ! run rm -fr "$MPI_FILE_UTILS_PATH/deps" "$MPI_FILE_UTILS_PATH/build" "$MPI_FILE_UTILS_PATH/configure" ; then
 			fatal "Old install of MPI File Utils could not be removed"
@@ -504,14 +499,14 @@ if [[ ${MPI_FILE_UTILS_PATH:+x} ]] ; then
 	popd > /dev/null
 fi
 
-if [[ ${IOR_PATH:+x} ]] ; then
+if [[ $IOR_PATH ]] ; then
 	info "Building and installing IOR from source tree $IOR_PATH to $DAOS_INSTALL_DIR"
 
 	if [[ ! -f "$IOR_PATH/src/ior.c" ]] ; then
 		fatal "Invalid IOR directory: path=$IOR_PATH"
 	fi
 
-	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
+	if [[ "$CMD" == install && -n "$FORCE_INSTALL" ]] ; then
 		info "Removing old IOR install"
 		if ! run rm -fr "$IOR_PATH/build" "$IOR_PATH/configure" ; then
 			fatal "Old install of IOR could not be removed"
@@ -537,32 +532,6 @@ if [[ ${IOR_PATH:+x} ]] ; then
 			--with-mpiio)
 
 		run ../configure "${IOR_CONFIGURE_OPTS[@]}"
-	fi
-
-	run env CFLAGS="-g -O0" make -j $(nproc) install
-
-	popd > /dev/null
-fi
-
-if [[ ${FIO_PATH:+x} ]] ; then
-	info "Building and installing FIO from source tree $FIO_PATH to $DAOS_INSTALL_DIR"
-
-	if [[ ! -f "$FIO_PATH/fio.c" ]] ; then
-		fatal "Invalid FIO: path=$FIO_PATH"
-	fi
-
-	if [[ "$CMD" == install ]] && "$FORCE_INSTALL" ; then
-		info "Removing old FIO install"
-		if ! run rm -fr "$FIO_PATH/build" ; then
-			fatal "Old install of FIO could not be removed"
-		fi
-	fi
-
-	run mkdir -p "$FIO_PATH/build"
-	pushd "$FIO_PATH/build" > /dev/null
-
-	if [[ ! -f "$FIO_PATH/build/Makefile" ]] ; then
-		run env CFLAGS="-I$DAOS_INSTALL_DIR/include" LDFLAGS="-L$DAOS_INSTALL_DIR/lib64" ../configure --prefix="$DAOS_INSTALL_DIR"
 	fi
 
 	run env CFLAGS="-g -O0" make -j $(nproc) install
