DAOS-14657 test: ftest for libpil4dfs with fio
Miscelllaneous improvements of the ansible ftest deployment scripts:
- support of fio.
- support of shared cluster and verbs provider.
- remove useless MPI configuration file.
- fix RPMs dependencies.

Required-githooks: true
Signed-off-by: Cedric Koch-Hofer <cedric.koch-hofer@intel.com>

diff --git a/utils/ansible/ftest/templates/daos-make.sh.j2 b/utils/ansible/ftest/templates/daos-make.sh.j2
--- a/utils/ansible/ftest/templates/daos-make.sh.j2
+++ b/utils/ansible/ftest/templates/daos-make.sh.j2
@@ -1,10 +1,10 @@
 #!/bin/bash
 # shellcheck disable=all # Jinja2 template can not be parsed with shellcheck
 
-set -o pipefail
+set -u -o pipefail
 
-VERSION=0.3
-CWD="$(realpath "$(dirname $0)")"
+VERSION=0.4
+CWD="$(realpath "$(dirname "$0")")"
 declare -A VALID_CMDS=([install]=true [update]=true)
 
 DAOS_INSTALL_DIR="{{ daos_runtime_dir }}/install"
@@ -13,6 +13,7 @@ SERVERS_LIST="{{ groups["daos_servers"] | join(',') }}"
 {% if "daos_clients" in groups and groups["daos_clients"] | length > 0 %}
 CLIENTS_LIST="{{ groups["daos_clients"] | join(',') }}"
 {% endif %}
+BUILD_TYPE="{{ daos_build_mode | default(daos_build_mode_default) }}"
 
 SCONS_EXE=scons-3
 CLUSH_EXE=clush
@@ -116,6 +117,7 @@ function usage
 		       --vol-daos <path>	Path of vol-daos source tree
 		       --mpifileutils <path>    Path of mpi file utils source tree
 		       --ior <path>             Path of ior file utils source tree
+		       --fio <path>             Path of fio file utils source tree
 		   -j, --jobs <job>             Allow N jobs at once; one job with no arg
 		   -f, --force                  Overwrite the current install of DAOS
 		   -h, --help                   Show this help message and exit
@@ -140,7 +142,7 @@ function run
 	fi
 }
 
-OPTIONS=$(getopt -o "j:fhVvDq" --long "mpich:,hdf5:,vol-daos:,mpifileutils:,ior:,jobs:,force,help,version,verbose,debug,quiet" -- "$@") || exit 1
+OPTIONS=$(getopt -o "j:fhVvDq" --long "mpich:,hdf5:,vol-daos:,mpifileutils:,ior:,fio:,jobs:,force,help,version,verbose,debug,quiet" -- "$@") || exit 1
 eval set -- "$OPTIONS"
 while true
 do
@@ -150,6 +152,7 @@ do
 		--vol-daos) VOL_DAOS_PATH="$2" ; shift 2 ;;
 		--mpifileutils) MPI_FILE_UTILS_PATH="$2" ; shift 2 ;;
 		--ior) IOR_PATH="$2" ; shift 2 ;;
+		--fio) FIO_PATH="$2" ; shift 2 ;;
 		-j|--jobs) JOBS_NB="$2" ; shift 2 ;;
 		-f|--force) FORCE_INSTALL=true ; shift 1;;
 		-h|--help) usage ; exit 0;;
@@ -205,7 +208,7 @@ case $CMD in
 esac
 
 info "Building and installing DAOS from source tree $PWD to $DAOS_INSTALL_DIR"
-if ! run env MPI_PKG=any "$SCONS_EXE" BUILD_TYPE=debug PREFIX="$DAOS_INSTALL_DIR" install $SCONS_OPTS ; then
+if ! run env MPI_PKG=any "$SCONS_EXE" BUILD_TYPE="$BUILD_TYPE" PREFIX="$DAOS_INSTALL_DIR" install $SCONS_OPTS ; then
 	fatal "DAOS could not be properly build and/or installed"
 fi
 
@@ -336,7 +339,7 @@ if [[ $MPICH_PATH ]] ; then
 		mkdir -p /usr/share/modulefiles/mpi
 		ln -fs "$DAOS_INSTALL_DIR/share/modulefiles/mpich-x86_64" /usr/share/modulefiles/mpi/mpich-x86_64
 		EOF
-	} | run $CLUSH_EXE $CLUSH_OPTS -l root -w $CLIENTS_LIST bash -s
+	} | run $CLUSH_EXE $CLUSH_OPTS -l root -w $CLIENTS_LIST -w $SERVERS_LIST bash -s
 fi
 
 if [[ $HDF5_PATH ]] ; then
@@ -532,6 +535,32 @@ if [[ $IOR_PATH ]] ; then
 			--with-mpiio)
 
 		run ../configure "${IOR_CONFIGURE_OPTS[@]}"
+	fi
+
+	run env CFLAGS="-g -O0" make -j $(nproc) install
+
+	popd > /dev/null
+fi
+
+if [[ $FIO_PATH ]] ; then
+	info "Building and installing FIO from source tree $FIO_PATH to $DAOS_INSTALL_DIR"
+
+	if [[ ! -f "$FIO_PATH/fio.c" ]] ; then
+		fatal "Invalid FIO: path=$FIO_PATH"
+	fi
+
+	if [[ "$CMD" == install && -n "$FORCE_INSTALL" ]] ; then
+		info "Removing old FIO install"
+		if ! run rm -fr "$FIO_PATH/build" ; then
+			fatal "Old install of FIO could not be removed"
+		fi
+	fi
+
+	run mkdir -p "$FIO_PATH/build"
+	pushd "$FIO_PATH/build" > /dev/null
+
+	if [[ ! -f "$FIO_PATH/build/Makefile" ]] ; then
+		run env CFLAGS="-I$DAOS_INSTALL_DIR/include" LDFLAGS="-L$DAOS_INSTALL_DIR/lib64" ../configure --prefix="$DAOS_INSTALL_DIR"
 	fi
 
 	run env CFLAGS="-g -O0" make -j $(nproc) install
