DAOS-17397 build: Support of el9 distribution with ansible ftest playbook
Generate compilation database (i.e. compile_commands.json) with bear.

Signed-off-by: Cedric Koch-Hofer <cedric.koch-hofer@hpe.com>

diff --git a/utils/ansible/ftest/templates/daos-make.sh.j2 b/utils/ansible/ftest/templates/daos-make.sh.j2
--- a/utils/ansible/ftest/templates/daos-make.sh.j2
+++ b/utils/ansible/ftest/templates/daos-make.sh.j2
@@ -27,6 +27,14 @@ MAKE_EXE=make
 WGET_EXE=wget
 PYTHON_EXE=python3.11
 PIP_EXE=pip
+BEAR_EXE=$( command -v bear )
+# NOTE bear LD_PRELOAD not supported with ASan library
+for it in $@ ; do
+	if [[ $it =~ ^SANITIZERS= ]] ; then
+		unset BEAR_EXE
+		break
+	fi
+done
 
 CLUSH_OPTS="-bL -S"
 
@@ -228,8 +236,14 @@ fi
 
 info "Building DAOS from source tree $DAOS_SOURCE_DIR"
 # NOTE Dependencies will not be build as 'no' is default value of the --build-deps option
-if ! run env MPI_PKG=any "$SCONS_EXE" BUILD_TYPE="$DAOS_BUILD_TYPE" BUILD_ROOT="$DAOS_BUILD_DIR" PREFIX="$DAOS_INSTALL_DIR" "${args[@]}" $SCONS_OPTS ; then
-	fatal "DAOS could not be properly build"
+if [[ ${BEAR_EXE:+x} ]] ; then
+	if ! run env MPI_PKG=any "$BEAR_EXE" --append --output "$DAOS_SOURCE_DIR/compile_commands.json" -- "$SCONS_EXE" BUILD_TYPE="$DAOS_BUILD_TYPE" BUILD_ROOT="$DAOS_BUILD_DIR" PREFIX="$DAOS_INSTALL_DIR" "${args[@]}" $SCONS_OPTS ; then
+		fatal "DAOS could not be properly build"
+	fi
+else
+	if ! run env MPI_PKG=any "$SCONS_EXE" BUILD_TYPE="$DAOS_BUILD_TYPE" BUILD_ROOT="$DAOS_BUILD_DIR" PREFIX="$DAOS_INSTALL_DIR" "${args[@]}" $SCONS_OPTS ; then
+		fatal "DAOS could not be properly build"
+	fi
 fi
 
 info "Installing DAOS to $DAOS_INSTALL_DIR"
