DAOS-11524 build: rpmlint resulting RPMs
Remove shebangs from non-executable scripts.

Update defaults to EL8.

Fix copyright githook to work on all files in the changeset, not just
the latest diff.

DRY base branch determination code in githooks.

Remove the arch from the stashed RPM version since we now have some
noarch packages.

Required-githooks: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

diff --git a/utils/githooks/pre-commit.d/10-update-copyright b/utils/githooks/pre-commit.d/10-update-copyright
--- a/utils/githooks/pre-commit.d/10-update-copyright
+++ b/utils/githooks/pre-commit.d/10-update-copyright
@@ -2,9 +2,9 @@
 
 # A git hook to validate and correct the copyright date in source files.
 
-if [ -e .git/MERGE_HEAD ]
-then
-    echo Merge commit
+echo "Copyright update:"
+if [ -e .git/MERGE_HEAD ]; then
+    echo "  Merge commit"
     exit 0
 fi
 
@@ -41,7 +41,19 @@ targets=(
 
 os=$(uname -s)
 
-files=${files:-$(git diff --diff-filter=AM --name-only --cached -- "${targets[@]}")}
+# shellcheck disable=SC1091
+. utils/githooks/find_base.sh
+
+if [ -z "$files" ]; then
+    if [ "$TARGET" = "HEAD" ]; then
+        echo "  Checking against HEAD"
+        files=$(git diff HEAD  --diff-filter=AM --name-only -- "${targets[@]}")
+    else
+        echo "  Checking against branch ${TARGET}"
+        files=$(git diff "$TARGET"... --diff-filter=AM --name-only -- "${targets[@]}")
+    fi
+fi
+
 for file in $files; do
 	if [[ "$file" == *vendor* ]] || [[ "$file" == *pb.go ]] || \
 	   [[ "$file" == *_string.go ]] || [[ "$file" == *pb-c* ]]; then
@@ -49,10 +61,10 @@ for file in $files; do
 	fi
 	read -r y1 y2 <<< "$(sed -nre "s/^.*$regex.*$/\4 \6/p" "$file")"
 	if [[ -z $y1 ]] ; then
-		echo "Copyright Information not found in: $file"
+		echo "  Copyright Information not found in: $file"
 		errors=$((errors + 1))
 	elif [[ $y1 -ne $year && $year -ne $y2 ]] ; then
-		git reset "$file" || (echo "Unable to un-stage $file" && exit 1)
+		git reset "$file" || (echo "  Unable to un-stage $file" && exit 1)
 		if [ "$os" == 'Linux' ]
 		then
 			sed -i -re "s/$regex/\1Copyright $y1-$year \8/" "$file"
@@ -60,7 +72,7 @@ for file in $files; do
 			sed -i '' -re "s/$regex/\1Copyright $y1-$year \8/" "$file"
 		fi
 
-		git add "$file" || (echo "Unable to re-stage $file" && exit 1)
+		git add "$file" || (echo "  Unable to re-stage $file" && exit 1)
 	fi
 done
-[[ $errors = 0 ]] || (echo "$errors errors while checking/fixing copyrights.")
+[[ $errors = 0 ]] || (echo "  $errors errors while checking/fixing copyrights.")
