Initial linting fixes
Skip-PR-comments: true

Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

diff --git a/utils/githooks/commit-msg.d/10-watermark b/utils/githooks/commit-msg.d/10-watermark
--- a/utils/githooks/commit-msg.d/10-watermark
+++ b/utils/githooks/commit-msg.d/10-watermark
@@ -1,5 +1,6 @@
 #!/bin/bash
 
-if ! grep 'Required-githooks: true' $1; then
-    echo 'Required-githooks: true' >> $1
+exit 0
+if ! grep 'Required-githooks: true' "$1"; then
+    echo 'Required-githooks: true' >> "$1"
 fi
