Address review comments
Skip-build: true
Skip-test: true

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

diff --git a/utils/githooks/pre-commit b/utils/githooks/pre-commit
--- a/utils/githooks/pre-commit
+++ b/utils/githooks/pre-commit
@@ -1,13 +1,21 @@
 #!/bin/bash
 
 # A git hook to validate  and correct the copyright date in source files.
+if [ -n "${NO_PRE_COMMIT:=""}" ]; then
+    exit 0
+fi
 
-regex='(^\s*\*.*)((Copyright\s*)([0-9]{4})(-([0-9]{4}))?)(\s*(Intel.*$))'
+regex='(^\s*[\*/].*)((Copyright\s*)([0-9]{4})(-([0-9]{4}))?)(\s*(Intel.*$))'
 year=$(date +%Y)
 errors=0
 
-files=$(git diff --diff-filter=AM --name-only --cached -- '*.c' '*.h' 'Makefile')
+files=$(git diff --diff-filter=AM --name-only --cached -- \
+       '*.c' '*.h' '*.go' 'Makefile')
 for file in $files; do
+    if [[ "$file" == *vendor* ]] || [[ "$file" == *pb.go ]] || \
+       [[ "$file" == *_string.go ]] || [[ "$file" == *pb-c* ]]; then
+        continue
+    fi
 	read -r y1 y2 <<< "$(sed -nre "s/^.*$regex.*$/\4 \6/p" "$file")"
 	if [[ -z $y1 ]] ; then
 		echo "Copyright Information not found in: $file"
@@ -18,4 +26,4 @@ for file in $files; do
 		git add "$file" || (echo "Unable to re-stage $file" && exit 1)
 	fi
 done
-[[ $errors = 0 ]] || (echo "Multiple errors encountered.")
+[[ $errors = 0 ]] || (echo "$errors errors while checking/fixing copyrights.")
