make all parameters optional, but with defaults
Signed-off-by: Tomasz Gromadzki <tomasz.gromadzki@hpe.com>

Priority: 2
Skip-unit-tests: true
Skip-test: true

diff --git a/utils/docker/Dockerfile.leap.15 b/utils/docker/Dockerfile.leap.15
--- a/utils/docker/Dockerfile.leap.15
+++ b/utils/docker/Dockerfile.leap.15
@@ -9,12 +9,14 @@
 # Use --target build-ci to create image with basic build environment for gcc
 
 # Global defaults
-ARG DAOS_TARGET_TYPE=release
 ARG DAOS_DEPS_BUILD=yes
 ARG DAOS_KEEP_BUILD=no
 ARG DAOS_PACKAGES_BUILD=yes
-ARG DEPS_JOBS=32
-ARG DAOS_PACKAGES_VERIFY=no
+ARG DAOS_PACKAGES_VERIFY=yes
+
+# Left empty on purpose: scons and the build scripts provide their own defaults.
+ARG DAOS_TARGET_TYPE=
+ARG DEPS_JOBS=
 
 # Pull base image
 ARG POINT_RELEASE=
@@ -82,6 +84,9 @@ FROM basic AS build-ci
 RUN --mount=type=bind,source=utils/scripts/install-leap15.sh,target=/tmp/daos/install.sh \
     INSTALL_BUILD_CI_ONLY="true" /tmp/daos/install.sh && \
     dnf clean all
+# Local container builds need the OpenMPI wrappers on PATH; Jenkins loads MPI
+# through Lmod before invoking scons.
+# ENV PATH=/usr/lib64/mpi/gcc/openmpi3/bin:$PATH
 
 # According to https://pkgs.org/search/?q=lua-lmod, Leap 15.6 only has lua-lmod-8.7.34.
 # This version has a problem with loading modules, as described in https://github.com/TACC/Lmod/issues/687.
@@ -149,10 +154,13 @@ RUN --mount=type=bind,source=SConstruct,target=/home/daos/pre/SConstruct \
     --mount=type=bind,source=utils/scripts/create_spdk_pkgconfig.sh,target=/home/daos/pre/utils/scripts/create_spdk_pkgconfig.sh \
     --mount=type=bind,source=utils/rpms/build_deps.sh,target=/home/daos/pre/utils/rpms/build_deps.sh \
     [ "$DAOS_DEPS_BUILD" != "yes" ] || { \
-        DAOS_DEPS_JOBS="$DEPS_JOBS" DAOS_TARGET_TYPE="$DAOS_TARGET_TYPE" \
-        utils/rpms/build_deps.sh && \
-        rm -rf .sconf_temp .sconsign.dblite config.log && \
-        ([ "$DAOS_KEEP_BUILD" != "no" ] || /bin/rm -rf build *.gz); \
+        utils/rpms/build_deps.sh \
+            ${DEPS_JOBS:+--jobs "$DEPS_JOBS"} \
+            ${DAOS_TARGET_TYPE:+TARGET_TYPE="$DAOS_TARGET_TYPE"} && \
+        [ "$DAOS_KEEP_BUILD" != "no" ] || { \
+            rm -rf .sconf_temp .sconsign.dblite config.log && \
+            /bin/rm -rf build *.gz; \
+        } ; \
     }
 
 # Build DAOS dependencies RPMs
@@ -187,7 +195,7 @@ LABEL DAOS=true
 ARG COMPILER=gcc
 ARG DAOS_DEPS_BUILD
 ARG DAOS_BUILD=$DAOS_DEPS_BUILD
-ARG DAOS_JAVA_BUILD=$DAOS_BUILD
+ARG DAOS_JAVA_BUILD=no
 
 # Install the rest of components if other than gcc compiler will be used for
 # DAOS or Java build is requested.
@@ -237,14 +245,17 @@ RUN --mount=type=bind,source=VERSION,target=/home/daos/daos/VERSION \
     --mount=type=bind,source=utils/certs,target=/home/daos/daos/utils/certs \
     --mount=type=bind,source=utils/completion,target=/home/daos/daos/utils/completion \
     --mount=type=bind,source=utils/config,target=/home/daos/daos/utils/config \
+    --mount=type=bind,source=utils/rpms/build_daos.sh,target=/home/daos/daos/utils/rpms/build_daos.sh \
     --mount=type=bind,source=src,target=/tmp/daos-src \
     [ "$DAOS_BUILD" != "yes" ] || { \
         export GOCACHE=/tmp/go-cache && \
         mkdir -p /home/daos/daos/src && \
         cp -r /tmp/daos-src/. /home/daos/daos/src && \
-           scons --jobs $JOBS install PREFIX=/opt/daos COMPILER=$COMPILER \
-               BUILD_TYPE=$DAOS_BUILD_TYPE TARGET_TYPE=$DAOS_TARGET_TYPE \
-        USE_INSTALLED=all && \
+           utils/rpms/build_daos.sh \
+           ${JOBS:+--jobs "$JOBS"} \
+           ${COMPILER:+COMPILER=$COMPILER} \
+           ${DAOS_BUILD_TYPE:+BUILD_TYPE="$DAOS_BUILD_TYPE"} \
+           ${DAOS_TARGET_TYPE:+TARGET_TYPE="$DAOS_TARGET_TYPE"} && \
         ([ "$DAOS_KEEP_BUILD" != "no" ] || { \
             /bin/rm -rf build; \
         }) && \
@@ -310,6 +321,15 @@ RUN --mount=type=bind,source=utils/scripts/helpers/maven-settings.xml.in,target=
             rm -rf /home/daos/daos/src; \
         }; \
     }
+
+WORKDIR /home/daos/rpms
+RUN createrepo . || echo "createrepo failed"
+
+WORKDIR /home/daos
+USER root:root
+RUN tar -C / -cf /home/daos/opt_daos.tar opt/daos || echo "tar failed"
+RUN chown daos_server.daos_server /home/daos/opt_daos.tar || true
+USER daos_server:daos_server
 
 # Setup docker image for Unit Tests
 FROM build-local AS full
