DAOS-14226 docker: deployment of vcluster with md-on-ssd
Integrate reviewers comments:
- Remove file not belonging to the PR
- Not return error with counter decrement
- Use env variable for version number

Doc-only: true
Required-githooks: true
Signed-off-by: Cedric Koch-Hofer <cedric.koch-hofer@intel.com>

diff --git a/utils/docker/examples/daos-client_agent/el8/Dockerfile b/utils/docker/examples/daos-client_agent/el8/Dockerfile
--- a/utils/docker/examples/daos-client_agent/el8/Dockerfile
+++ b/utils/docker/examples/daos-client_agent/el8/Dockerfile
@@ -4,23 +4,29 @@
 # 'recipe' for building a base RHEL DAOS client docker image
 #
 # This Dockerfile accept the following input build arguments:
-# - LINUX_DISTRO             Linux distribution identifier (default "el8")
-# - DAOS_DOCKER_IMAGE_NSP    Namespace identifier of the base DAOS docker image (default "daos")
-# - DAOS_DOCKER_IMAGE_TAG    Tag identifier of the DAOS client docker image (default "v2.4.1")
-# - DAOS_VERSION             Version of DAOS to use (default "2.4.1-2.el8")
+# - LINUX_DISTRO             Linux distribution identifier (mandatory)
+# - DAOS_DOCKER_IMAGE_NSP    Namespace identifier of the base DAOS docker image (mandatory)
+# - DAOS_DOCKER_IMAGE_TAG    Tag identifier of the DAOS client docker image (mandatory)
+# - DAOS_VERSION             Version of DAOS to use (mandatory)
 # - DAOS_CLIENT_UNAME        User name of the client (mandatory)
 # - DAOS_CLIENT_GNAME        Group name of the client (mandatory)
 
 # Pull base image
-ARG	LINUX_DISTRO="el8"
-ARG	DAOS_DOCKER_IMAGE_NSP="daos"
-ARG	DAOS_DOCKER_IMAGE_TAG="v2.4.1"
+ARG	LINUX_DISTRO=""
+ARG	DAOS_DOCKER_IMAGE_NSP=""
+ARG	DAOS_DOCKER_IMAGE_TAG=""
 FROM	"$DAOS_DOCKER_IMAGE_NSP/daos-agent-$LINUX_DISTRO:$DAOS_DOCKER_IMAGE_TAG"
 LABEL	maintainer="daos@daos.groups.io"
 
 # Install base DAOS package
-ARG	DAOS_VERSION="2.4.1-2.el8"
-RUN	echo "[INFO] Installing DAOS containerization dependencies" ;                              \
+ARG	DAOS_VERSION=""
+RUN	for it in DAOS_VERSION ; do                                                                \
+		if eval "[[ -z \$$it ]]" ; then                                                    \
+			echo "[ERROR] Docker build argument $it is not defined" ;                  \
+			exit 1 ;                                                                   \
+		fi ;                                                                               \
+	done &&                                                                                    \
+	echo "[INFO] Installing DAOS containerization dependencies" ;                              \
 	dnf install                                                                                \
 		sudo                                                                               \
 		xz &&                                                                              \
diff --git a/utils/docker/vcluster/daos-admin/el8/Dockerfile b/utils/docker/vcluster/daos-admin/el8/Dockerfile
--- a/utils/docker/vcluster/daos-admin/el8/Dockerfile
+++ b/utils/docker/vcluster/daos-admin/el8/Dockerfile
@@ -3,38 +3,44 @@
 #
 # 'recipe' for building a RHEL variant docker image of a DAOS administrator node
 #
-#
-# - LINUX_DISTRO             Linux distribution identifier (default "el8")
-# - DAOS_DOCKER_IMAGE_NSP    Namespace identifier of the base DAOS docker image (default "daos")
-# - DAOS_DOCKER_IMAGE_TAG    Tag identifier of the DAOS base docker image (default "v2.4.1")
-# - DAOS_VERSION             Version of DAOS to use (default "2.4.1-2.el8")
-# - DAOS_AUTH                Enable DAOS authentication when set to "yes" (default "yes")
+# - LINUX_DISTRO             Linux distribution identifier (mandatory)
+# - DAOS_DOCKER_IMAGE_NSP    Namespace identifier of the base DAOS docker image (mandatory)
+# - DAOS_DOCKER_IMAGE_TAG    Tag identifier of the DAOS client docker image (mandatory)
+# - DAOS_VERSION             Version of DAOS to use (mandatory)
+# - DAOS_AUTH                Enable DAOS authentication when set to "yes" (mandatory)
 
 # Pull base image
-ARG	LINUX_DISTRO="el8"
-ARG	DAOS_DOCKER_IMAGE_NSP="daos"
-ARG	DAOS_DOCKER_IMAGE_TAG="v2.4.1"
+ARG	LINUX_DISTRO=""
+ARG	DAOS_DOCKER_IMAGE_NSP=""
+ARG	DAOS_DOCKER_IMAGE_TAG=""
 FROM	"${DAOS_DOCKER_IMAGE_NSP}/daos-base-${LINUX_DISTRO}:$DAOS_DOCKER_IMAGE_TAG"
 LABEL	maintainer="daos@daos.groups.io"
 
 # Install DAOS client package
-ARG	DAOS_VERSION="2.4.1-2.el8"
-RUN	dnf install daos-admin-${DAOS_VERSION} &&                                                  \
+ARG	DAOS_VERSION=""
+RUN	for it in DAOS_VERSION ; do                                                                \
+		if eval "[[ -z \$$it ]]" ; then                                                    \
+			echo "[ERROR] Docker build argument $it is not defined" ;                  \
+			exit 1 ;                                                                   \
+		fi ;                                                                               \
+	done &&                                                                                    \
+	dnf install daos-admin-${DAOS_VERSION} &&                                                  \
 	dnf clean all
 
 # Install certificates
-ARG	DAOS_AUTH=yes
-# FIXME Should be provided through volumes (or Secrets for K8S)
-# XXX NOTE XXX With a production platform, this configuration file should be provided with a volume
-# XXX NOTE XXX (or ConfigMaps for K8S).
 COPY	daos_control.yml.in /tmp/daos_control.yml.in
-RUN	if [ "$DAOS_AUTH" == yes ] ; then                                                          \
+ARG	DAOS_AUTH=""
+RUN	for it in DAOS_AUTH ; do                                                                   \
+		if eval "[[ -z \$$it ]]" ; then                                                    \
+			echo "[ERROR] Docker build argument $it is not defined" ;                  \
+			exit 1 ;                                                                   \
+		fi ;                                                                               \
+	done &&                                                                                    \
+	if [ "$DAOS_AUTH" == yes ] ; then                                                          \
 		sed --regexp-extended                                                              \
 		    --expression '/^@DAOS_NOAUTH_BEGIN@$/,/^@DAOS_NOAUTH_END@/d'                   \
 		    --expression '/(^@DAOS_AUTH_BEGIN@$)|(^@DAOS_AUTH_END@$)/d'                    \
 		    /tmp/daos_control.yml.in > /etc/daos/daos_control.yml &&                       \
-# XXX WARNING XXX With a production platform, these certificates should be provided with a volume
-# XXX WARNING XXX (or Secrets with K8S).
 		chmod 644 /root/daosCA/certs/daosCA.crt &&                                         \
 		chmod 644 /root/daosCA/certs/admin.crt &&                                          \
 		chmod 400 /root/daosCA/certs/admin.key &&                                          \
diff --git a/utils/docker/vcluster/daos-base/el8/Dockerfile b/utils/docker/vcluster/daos-base/el8/Dockerfile
--- a/utils/docker/vcluster/daos-base/el8/Dockerfile
+++ b/utils/docker/vcluster/daos-base/el8/Dockerfile
@@ -4,21 +4,19 @@
 # 'recipe' for building a base RHEL variant docker image of a DAOS node
 #
 # This Dockerfile accept the following input build arguments:
-# - LINUX_IMAGE_NAME    Base docker image name to use (default "rockylinux/rockylinux")
-# - LINUX_IMAGE_TAG     Tag identifier of the base docker image to use (default "8.9")
+# - LINUX_IMAGE_NAME    Base docker image name to use (mandatory)
+# - LINUX_IMAGE_TAG     Tag identifier of the base docker image to use (mandatory)
 # - BUST_CACHE          Manage docker building cache (default "").  To invalidate the cache,
 #                       a random value such as the date of day shall be given.
-# - DAOS_AUTH           Enable DAOS authentication when set to "yes" (default "yes")
-# - DAOS_REPOS          Space separated list of repos needed to install DAOS (default
-#                       "https://packages.daos.io/v2.4.1/EL8/packages/x86_64/")
-# - DAOS_GPG_KEYS       Space separated list of GPG keys associated with DAOS repos (default
-#                       "https://packages.daos.io/v2.4.1/RPM-GPG-KEY-2023"
-# - DAOS_REPOS_NOAUTH   Space separated list of repos to use without GPG authentication (default "")
-# - DAOS_VERSION        Version of DAOS to use (default "2.4.1-2.el8")
+# - DAOS_AUTH           Enable DAOS authentication when set to "yes" (mandatory)
+# - DAOS_REPOS          Space separated list of repos needed to install DAOS (mandatory)
+# - DAOS_GPG_KEYS       Space separated list of GPG keys associated with DAOS repos mandatory)
+# - DAOS_REPOS_NOAUTH   Space separated list of repos to use without GPG authentication (optional)
+# - DAOS_VERSION        Version of DAOS to use (mandatory)
 
 # Pull base image
-ARG	LINUX_IMAGE_NAME=rockylinux/rockylinux
-ARG	LINUX_IMAGE_TAG="8.9"
+ARG	LINUX_IMAGE_NAME=""
+ARG	LINUX_IMAGE_TAG=""
 FROM	$LINUX_IMAGE_NAME:$LINUX_IMAGE_TAG
 LABEL	maintainer="daos@daos.groups.io"
 
@@ -38,11 +36,17 @@ RUN	dnf clean all &&                                                            
 # XXX NOTE XXX to not update all rpms.  To work properly a random value such as the date of the day
 # XXX NOTE XXX should be given.
 ARG	BUST_CACHE=""
-ARG	DAOS_REPOS="https://packages.daos.io/v2.4.1/EL8/packages/x86_64/"
-ARG	DAOS_GPG_KEYS="https://packages.daos.io/v2.4.1/RPM-GPG-KEY-2023"
-ARG	DAOS_VERSION="2.4.1-2.el8"
+ARG	DAOS_REPOS=""
+ARG	DAOS_GPG_KEYS=""
+ARG	DAOS_VERSION=""
 ARG	DAOS_REPOS_NOAUTH=""
-RUN	if [ -n "$BUST_CACHE" ] ; then                                                             \
+RUN	for it in DAOS_REPOS DAOS_GPG_KEYS DAOS_VERSION ; do                                       \
+		if eval "[[ -z \$$it ]]" ; then                                                    \
+			echo "[ERROR] Docker build argument $it is not defined" ;                  \
+			exit 1 ;                                                                   \
+		fi ;                                                                               \
+	done &&                                                                                    \
+	if [ -n "$BUST_CACHE" ] ; then                                                             \
 		echo "[INFO] Busting cache" &&                                                     \
 		dnf update ;                                                                       \
 	fi &&                                                                                      \
@@ -63,8 +67,14 @@ RUN	if [ -n "$BUST_CACHE" ] ; then                                              
 	dnf clean all
 
 # Generate GPG authentication certificates for using DAOS authentication
-ARG	DAOS_AUTH=yes
-RUN	if [ "$DAOS_AUTH" == yes ] ; then                                                          \
+ARG	DAOS_AUTH=""
+RUN	for it in DAOS_AUTH ; do                                                                   \
+		if eval "[[ -z \$$it ]]" ; then                                                    \
+			echo "[ERROR] Docker build argument $it is not defined" ;                  \
+			exit 1 ;                                                                   \
+		fi ;                                                                               \
+	done &&                                                                                    \
+	if [ "$DAOS_AUTH" == yes ] ; then                                                          \
 		echo "[INFO] Generating authentication certificates" &&                            \
 		if [ ! -d /etc/daos/certs ] ; then                                                 \
 			mkdir -d /etc/daos/certs &&                                                \
diff --git a/utils/docker/vcluster/daos-client/el8/Dockerfile b/utils/docker/vcluster/daos-client/el8/Dockerfile
--- a/utils/docker/vcluster/daos-client/el8/Dockerfile
+++ b/utils/docker/vcluster/daos-client/el8/Dockerfile
@@ -4,39 +4,52 @@
 # 'recipe' for building a RHEL variant docker image of a DAOS client node
 #
 # This Dockerfile accept the following input build arguments:
-# - LINUX_DISTRO                   Linux distribution identifier (default "el8")
-# - DAOS_DOCKER_IMAGE_NSP          Namespace identifier of the base DAOS docker image (default "daos")
-# - DAOS_DOCKER_IMAGE_TAG          Tag identifier of the DAOS base docker image to use (default "rocky8.6")
-# - DAOS_VERSION                   Version of DAOS to use (default "2.4.1-2.el8")
-# - DAOS_AUTH                      Enable DAOS authentication when set to "yes" (default "yes")
+# - LINUX_DISTRO                   Linux distribution identifier (mandatory)
+# - DAOS_DOCKER_IMAGE_NSP          Namespace identifier of the base DAOS docker image (mandatory)
+# - DAOS_DOCKER_IMAGE_TAG          Tag identifier of the DAOS client docker image (mandatory)
+# - DAOS_VERSION                   Version of DAOS to use (mandatory)
+# - DAOS_AUTH                      Enable DAOS authentication when set to "yes" (mandatory)
 # - DAOS_AGENT_IFACE_CFG           Enable manual configuration of the interface to use by the agent
-#                                  (default "yes")
-# - DAOS_AGENT_IFACE_NUMA_NODE     Numa node of the interface to use by the agent (default "0")
-# - DAOS_AGENT_IFACE_NAME          Name of the interface to use by the agent (default "eth0")
-# - DAOS_AGENT_IFACE_DOMAIN_NAME   Domain name of the interface to use by the agent (default "eth0")
+#                                  (mandatory)
+# - DAOS_AGENT_IFACE_NUMA_NODE     Numa node of the interface to use by the agent (mandatory)
+# - DAOS_AGENT_IFACE_NAME          Name of the interface to use by the agent (mandatory)
+# - DAOS_AGENT_IFACE_DOMAIN_NAME   Domain name of the interface to use by the agent (mandatory)
 
 # Pull base image
-ARG	LINUX_DISTRO="el8"
-ARG	DAOS_DOCKER_IMAGE_NSP="daos"
-ARG	DAOS_DOCKER_IMAGE_TAG="v2.4.1"
+ARG	LINUX_DISTRO=""
+ARG	DAOS_DOCKER_IMAGE_NSP=""
+ARG	DAOS_DOCKER_IMAGE_TAG=""
 FROM	"${DAOS_DOCKER_IMAGE_NSP}/daos-base-${LINUX_DISTRO}:$DAOS_DOCKER_IMAGE_TAG"
 LABEL	maintainer="daos@daos.groups.io"
 
 # Install DAOS client package
-ARG	DAOS_VERSION="2.4.1-2.el8"
-RUN	dnf install                                                                                \
+ARG	DAOS_VERSION=""
+RUN	for it in DAOS_VERSION ; do                                                                \
+		if eval "[[ -z \$$it ]]" ; then                                                    \
+			echo "[ERROR] Docker build argument $it is not defined" ;                  \
+			exit 1 ;                                                                   \
+		fi ;                                                                               \
+	done &&                                                                                    \
+	dnf install                                                                                \
 		daos-client-${DAOS_VERSION} &&                                                     \
 	dnf clean all &&                                                                           \
 	systemctl enable daos_agent
 
 # Install certificates
-ARG	DAOS_AUTH=yes
-ARG	DAOS_AGENT_IFACE_CFG="yes"
-ARG	DAOS_AGENT_IFACE_NUMA_NODE="0"
-ARG	DAOS_AGENT_IFACE_NAME="eth0"
-ARG	DAOS_AGENT_IFACE_DOMAIN_NAME="eth0"
+ARG	DAOS_AUTH=""
+ARG	DAOS_AGENT_IFACE_CFG=""
+ARG	DAOS_AGENT_IFACE_NUMA_NODE=""
+ARG	DAOS_AGENT_IFACE_NAME=""
+ARG	DAOS_AGENT_IFACE_DOMAIN_NAME=""
 COPY	daos_agent.yml.in /tmp/daos_agent.yml.in
-RUN	if [ "$DAOS_AUTH" == yes ] ; then                                                          \
+RUN	for it in DAOS_AUTH DAOS_AGENT_IFACE_CFG DAOS_AGENT_IFACE_NUMA_NODE DAOS_AGENT_IFACE_NAME  \
+		  DAOS_AGENT_IFACE_DOMAIN_NAME ; do                                                \
+		if eval "[[ -z \$$it ]]" ; then                                                    \
+			echo "[ERROR] Docker build argument $it is not defined" ;                  \
+			exit 1 ;                                                                   \
+		fi ;                                                                               \
+	done &&                                                                                    \
+	if [ "$DAOS_AUTH" == yes ] ; then                                                          \
 		sed --in-place --regexp-extended                                                   \
 			--expression '/^@DAOS_NOAUTH_BEGIN@$/,/^@DAOS_NOAUTH_END@/d'               \
 			--expression '/(^@DAOS_AUTH_BEGIN@$)|(^@DAOS_AUTH_END@$)/d'                \
