Try setting the year in CI.
Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>

diff --git a/ci/patch_src_in_place b/ci/patch_src_in_place
--- a/ci/patch_src_in_place
+++ b/ci/patch_src_in_place
@@ -12,6 +12,21 @@ codespell -w --ignore-words-list dedup,nd,uint,ths,ba,creat,te,cas,mapp,pres,cra
 # CORCI-988 tracks this, with a view to improving reporting in this case.
 RC=$?
 
+# Apply the year change patch.
+regex='(^\s*[\*/].*)((Copyright\s*)([0-9]{4})(-([0-9]{4}))?)(\s*(Intel.*$))'
+year=$(date +%Y)
+mapfile -t sfiles < <(git diff --name-only origin/"$CHANGE_TARGET"...)
+for file in "${sfiles[@]}"
+do
+    read -r y1 y2 <<< "$(sed -nre "s/^.*$regex.*$/\4 \6/p" "$file")"
+    if [[ -z $y1 ]] ; then
+	echo "Copyright Information not found in: $file"
+	errors=$((errors + 1))
+    elif [[ $y1 -ne $year && $year -ne $y2 ]] ; then
+	sed -i -re "s/$regex/\1Copyright $y1-$year \8/" "$file" || exit 1
+    fi
+done
+
 def_ignore="SPLIT_STRING,SSCANF_TO_KSTRTO,PREFER_KERNEL_TYPES"
 def_ignore+=",USE_NEGATIVE_ERRNO,CAMELCASE,STATIC_CONST_CHAR_ARRAY"
 def_ignore+=",COMPARISON_TO_NULL,COMPLEX_MACRO,BIT_MACRO"
diff --git a/utils/githooks/pre-commit b/utils/githooks/pre-commit
--- a/utils/githooks/pre-commit
+++ b/utils/githooks/pre-commit
@@ -16,14 +16,14 @@ for file in $files; do
        [[ "$file" == *_string.go ]] || [[ "$file" == *pb-c* ]]; then
         continue
     fi
-	read -r y1 y2 <<< "$(sed -nre "s/^.*$regex.*$/\4 \6/p" "$file")"
-	if [[ -z $y1 ]] ; then
-		echo "Copyright Information not found in: $file"
-		errors=$((errors + 1))
-	elif [[ $y1 -ne $year && $year -ne $y2 ]] ; then
-		git reset "$file" || (echo "Unable to un-stage $file" && exit 1)
-		sed -i -re "s/$regex/\1Copyright $y1-$year \8/" "$file" || exit 1
-		git add "$file" || (echo "Unable to re-stage $file" && exit 1)
-	fi
+    read -r y1 y2 <<< "$(sed -nre "s/^.*$regex.*$/\4 \6/p" "$file")"
+    if [[ -z $y1 ]] ; then
+	echo "Copyright Information not found in: $file"
+	errors=$((errors + 1))
+    elif [[ $y1 -ne $year && $year -ne $y2 ]] ; then
+	git reset "$file" || (echo "Unable to un-stage $file" && exit 1)
+	sed -i -re "s/$regex/\1Copyright $y1-$year \8/" "$file" || exit 1
+	git add "$file" || (echo "Unable to re-stage $file" && exit 1)
+    fi
 done
 [[ $errors = 0 ]] || (echo "$errors errors while checking/fixing copyrights.")
