Handle cluster request cancelling
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: true
Skip-func-test-leap15: false

Required-githooks: true


#Pragmas from previous commit message:
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: true
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: false
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: true
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: false
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: false
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: true
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: false
Skip-func-test-leap15: false
Test-tag: always_passes always_fails
PR-repos: daos@PR-11702:153
Skip-func-test-leap15: false
Test-tag: always_passes always_fails
PR-repos: daos@PR-11702:153
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: false
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: false
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: true
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: true
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-build-el8-rpm: true
Skip-func-test-leap15: false
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Provisioning-pool: bmurrell-automate
Test-tag: always_passes always_fails
Skip-checkpatch: true
Skip-python-bandit: true
Skip-build: true
Quick-build: true
Quick-Functional: true
Allow-unstable-test: true
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

diff --git a/.github/workflows/rpm-build-and-test.yml b/.github/workflows/rpm-build-and-test.yml
--- a/.github/workflows/rpm-build-and-test.yml
+++ b/.github/workflows/rpm-build-and-test.yml
@@ -490,19 +490,39 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.GHA_RUNNER_POC }}
       - name: Request and Provision a Cluster
-        run: uuid=$(uuidgen);
-             echo "CLUSTER_REQUEST_UUID=$uuid" >> $GITHUB_ENV;
-             url='https://build.hpdd.intel.com/job/Get%20a%20cluster/buildWithParameters?token=mytoken&LABEL=stage_waittest_vm9&'"UUID=$uuid";
-             curl -v -X POST --user ${{ secrets.JENKINS_TOKEN }} "$url";
+        run: |
+             uuid=$(uuidgen)
+             echo "CLUSTER_REQUEST_UUID=$uuid" >> $GITHUB_ENV
+             url='https://build.hpdd.intel.com/job/Get%20a%20cluster/buildWithParameters?token=mytoken&LABEL=stage_waittest_vm9&'"UUID=$uuid"
+             if ! queue_url=$(curl -D - -f -v -X POST --user ${{ secrets.JENKINS_TOKEN }} "$url" |
+                              sed -ne '/Location/s/.*: //p'); then
+                 echo "Failed to request a cluster."
+                 exit 1
+             fi
+             curl -f --user ${{ secrets.JENKINS_TOKEN }} "$queue_url" | jq -r .why
              while [ ! -f /scratch/Get\ a\ cluster/"$uuid" ]; do
-                 echo "Waiting for a cluster";
-                 sleep 1;
-             done;
-             NODESTRING=$(cat /scratch/Get\ a\ cluster/$uuid);
-             echo "NODESTRING=$NODESTRING" >> $GITHUB_ENV;
-             echo "NODELIST=$NODESTRING" >> $GITHUB_ENV;
-             echo "NODE_COUNT=$(echo "$NODESTRING" | tr ',' ' ' | wc -w)" >> $GITHUB_ENV;
-             cat $GITHUB_ENV;
+                 echo "Waiting for a cluster"
+                 if [ $((SECONDS % 10)) -eq 0 ]; then
+                     { read -r cancelled; read -r reason; } <
+                         <(curl -sf --user ${{ secrets.JENKINS_TOKEN }} "$queue_url" |
+                           jq -r .cancelled,.why)
+                     if [ "$cancelled" == "true" ]; then
+                         echo "Cluster request cancelled from Jenkins"
+                         exit 1
+                     fi
+                     echo "$why"
+                 fi
+                 sleep 1
+             done
+             NODESTRING=$(cat /scratch/Get\ a\ cluster/$uuid)
+             if [ "$NODESTRING" = "cancelled" ]; then
+                 echo "Cluster request cancelled from Jenkins"
+                 exit 1
+             fi
+             echo "NODESTRING=$NODESTRING" >> $GITHUB_ENV
+             echo "NODELIST=$NODESTRING" >> $GITHUB_ENV
+             echo "NODE_COUNT=$(echo "$NODESTRING" | tr ',' ' ' | wc -w)" >> $GITHUB_ENV
+             cat $GITHUB_ENV
              ssh -oPasswordAuthentication=false -v root@${NODESTRING%%vm*} \
                  "POOL=${{ env.cp_PROVISIONING_POOL }}
                   NODESTRING=$NODESTRING
